baseURL = 'https://ctrabold.github.io/weltreisender'
title = 'Christian Trabold - Reise Blog - Weltreisender'
theme = ['hugo-book']

languageCode = 'de-de'
defaultContentLanguage = 'de'

copyright = '[Â© CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode.en)'
enableGitInfo = true

[[module.imports]]
  path = 'github.com/hugomods/shortcodes'

[[module.imports]]
  path = 'github.com/hugomods/images'

[params]
  BookTheme = 'auto'
  BookComments = false
  BookSearch = false
  #BookLastChangeLink = 'https://github.com/ctrabold/weltreisender/commit/{{ .GitInfo.Hash }}'
  #BookEditLink = 'https://github.com/ctrabold/weltreisender/edit/main/{{ .Path }}'

[params.hugomods]
  [params.hugomods.images]
    modern_format = 'webp'

[markup]
[markup.goldmark.renderer]
  unsafe = true
[markup.tableOfContents]
  startLevel = 3

[menu]
[[menu.after]]
  name = 'Schlagworte'
  pageRef = '/posts'
  weight = 10

[[menu.after]]
  name = 'Website'
  url = 'https://christian-trabold.de/'
  weight = 40

[[menu.after]]
  name = 'Bilder'
  url = 'https://www.flickr.com/photos/christian-trabold/'
  weight = 50
